Fix version regex
hashicorp/learn-terraform-enforce-policies pull request #15
Opened 2022-03-01 21:52 UTC by ritsok

2022-03-01 22:15 UTC, im2nguyen approved these changes

2022-03-02 15:35 UTC, robin-norwood requested changes

2022-03-02 15:35 UTC, robin-norwood commented on allowed-terraform-version.sentinel
> +  tfplan.terraform_version matches "^(0\\.1(4|5)|1\\.\\d)\\.\\d+$"
I don't think this works for two digit minor versions, like `1.11.0`. I think we want `"^(0\\.1(4|5)|1\\.\\d+)\\.\\d+$"` instead.

2022-03-02 20:26 UTC, ritsok commented on allowed-terraform-version.sentinel
> +  tfplan.terraform_version matches "^(0\\.1(4|5)|1\\.\\d)\\.\\d+$"
```suggestion
  tfplan.terraform_version matches "^(0\\.1(4|5)|1\\.\\d+)\\.\\d+$"
```

2022-03-02 21:45 UTC, merged